import React from 'react'
import { BrowserRouter, Routes, Route } from 'react-router-dom'
import ParallaxAlice from '../ParallaxAlice/Parallax'
import ParallaxRocket  from '../ParallaxRocket/Parallax'
import LandingPage from '../Components/LandingPage'

const Paths = () => {
  return (
    <div className='Paths'>
        <BrowserRouter>
            <Routes>
                <Route path="/Parallax-Alice" element={<ParallaxAlice></ParallaxAlice>} ></Route>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                <Route path="/Parallax-Rocket" element={<ParallaxRocket></ParallaxRocket>} ></Route>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                <Route path="/" element={<LandingPage/>} ></Route>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          "
                {/* <Route path="/" element={c} ></Route>" */}
                {/*<Route path="*" element={<ErrorPage></ErrorPage>} ></Route> */} 
            </Routes>
        </BrowserRouter>
    </div>
  )
}

export default Paths